---
# tasks file for ansible-role-chrony
- name: Install
  ansible.builtin.package:
    name: chrony
    state: present

- name: Config file
  ansible.builtin.template:
    src: "templates/chrony.conf.j2"
    dest: "/etc/chrony/chrony.conf"
    owner: root
    group: root
    mode: '644'
  notify: Restart chrony

- name: Service enabled and started
  ansible.builtin.service:
    name: "{{ chrony_service_name }}"
    enabled: true
    state: started
